module('love.filesystem')

function append() end
function areSymlinksEnabled() end
function createDirectory() end
function getAppdataDirectory() end
function getCRequirePath() end
function getDirectoryItems() end
function getIdentity() end
function getInfo() end
function getRealDirectory() end
function getRequirePath() end
function getSaveDirectory() end
function getSource() end
function getSourceBaseDirectory() end
function getUserDirectory() end
function getWorkingDirectory() end
function init() end
function isFused() end
function lines() end
function load() end
function mount() end
function newFile() end
function newFileData() end
function read() end
function remove() end
function setCRequirePath() end
function setIdentity() end
function setRequirePath() end
function setSource() end
function setSymlinksEnabled() end
function unmount() end
function write() end
