module('love.graphics')

function arc() end
function circle() end
function clear() end
function draw() end
function getBackgroundColor() end
function getBlendMode() end
function getCanvas() end
function getCanvasFormats() end
function getColor() end
function getColorMask() end
function getCompressedImageFormats() end
function getDefaultFilter() end
function getDimensions() end
function getFSAA() end
function getFont() end
function getHeight() end
function getLineJoin() end
function getLineStyle() end
function getLineWidth() end
function getFullscreenModes() end
function getShader() end
function getStats() end
function getSystemLimit() end
function getPointSize() end
function getPointStyle() end
function getRendererInfo() end
function getScissor() end
function getWidth() end
function isSupported() end
function isWireframe() end
function line() end
function newCanvas() end
function newFont() end
function newMesh() end
function newImage() end
function newImageFont() end
function newParticleSystem() end
function newShader() end
function newQuad() end
function newScreenshot() end
function newSpriteBatch() end
function origin() end
function point() end
function polygon() end
function pop() end
function present() end
function print() end
function printf() end
function push() end
function rectangle() end
function reset() end
function rotate() end
function scale() end
function setBackgroundColor() end
function setBlendMode() end
function setCanvas() end
function setColor() end
function setColorMask() end
function setDefaultFilter() end
function setFont() end
function setInvertedStencil() end
function setLineJoin() end
function setLineStyle() end
function setLineWidth() end
function setNewFont() end
function setShader() end
function setPointSize() end
function setPointStyle() end
function setScissor() end
function setWireframe() end
function setStencil() end
function shear() end
function translate() end
