module('love')
function draw() end
function errhand() end
function focus() end
function gamepadaxis() end
function gamepadpressed() end
function gamepadreleased() end
function joystickadded() end
function joystickaxis() end
function joystickhat() end
function joystickpressed() end
function joystickreleased() end
function joystickremoved() end
function keypressed() end
function keyreleased() end
function load() end
function mousefocus() end
function mousemoved() end
function mousepressed() end
function mousereleased() end
function quit() end
function resize() end
function run() end
function textinput() end
function threaderror() end
function update() end
function visible() end
function getVersion() end
