module('love')
function conf() end
function directorydropped() end
function draw() end
function errhand() end
function filedropped() end
function focus() end
function gamepadaxis() end
function gamepadpressed() end
function gamepadreleased() end
function joystickadded() end
function joystickaxis() end
function joystickhat() end
function joystickpressed() end
function joystickreleased() end
function joystickremoved() end
function keypressed() end
function keyreleased() end
function load() end
function lowmemory() end
function mousefocus() end
function mousemoved() end
function mousepressed() end
function mousereleased() end
function quit() end
function resize() end
function run() end
function textedited() end
function textinput() end
function threaderror() end
function touchmoved() end
function touchpressed() end
function touchreleased() end
function update() end
function visible() end
function wheelmoved() end
function getVersion() end
