module('love.window')

function close() end
function fromPixels() end
function getDisplayName() end
function getFullscreen() end
function getFullscreenModes() end
function getIcon() end
function getMode() end
function getPixelScale() end
function getPosition() end
function getTitle() end
function hasFocus() end
function hasMouseFocus() end
function isDisplaySleepEnabled() end
function isMaximized() end
function isOpen() end
function isVisible() end
function maximize() end
function minimize() end
function requestAttention() end
function setDisplaySleepEnabled() end
function setFullscreen() end
function setIcon() end
function setMode() end
function setPosition() end
function setTitle() end
function showMessageBox() end
function toPixels() end
